runserver:
	uv run python manage.py runserver

makemigrations:
	uv run python manage.py makemigrations

migrate:
	uv run python manage.py migrate

migrate-all: makemigrations migrate

createsuperuser:
	uv run python manage.py createsuperuser

shell:
	uv run python manage.py shell